name: Security

on:
  push:
    branches: [ main, develop, special_slot ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security checks weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    
    - name: Run Safety (dependency vulnerability check)
      run: |
        safety check || true
    
    - name: Run Bandit (security linter)
      run: |
        bandit -r . -f json || true